const express = require('express');
const authController = require('../controllers/authController');
const aboutController = require('../controllers/aboutController');
const helpController = require('../controllers/helpController');
const guideController = require('../controllers/guideController');
const legalController = require('../controllers/legalController');
const landingController = require('../controllers/landingController');
const publicPodcastController = require('../controllers/publicPodcastController');
const seoController = require('../controllers/seoController');
const shareController = require('../controllers/shareController');
const settingsController = require('../controllers/settingsController');
const { requireGuest } = require('../middleware/auth');

const router = express.Router();
router.get('/robots.txt', seoController.showRobotsTxt);
router.get('/sitemap.xml', seoController.showSitemapXml);
router.post('/language', settingsController.updateLanguagePreference);
router.get('/oauth2callback', requireGuest, authController.googleCallback);
router.get('/lab', landingController.showLanding);
router.get('/generate-episode', landingController.showLanding);
router.get('/podcast-idea-generator', landingController.showPodcastIdeaGenerator);
router.get('/examples', landingController.showExampleLibrary);
router.get('/guides', guideController.showGuidesIndex);
router.get('/guides/:slug', guideController.showGuide);
router.get('/share/:token', shareController.showSharedEpisode);
router.get('/podcasts/:showSlug/feed.xml', publicPodcastController.showPodcastFeed);
router.get('/podcasts/:showSlug/embed', publicPodcastController.showPodcastEmbed);
router.get('/podcasts/:showSlug/:episodeSlug/embed', publicPodcastController.showEpisodeEmbed);
router.get('/podcasts/:showSlug', publicPodcastController.showPublishedShow);
router.get('/podcasts/:showSlug/:episodeSlug', publicPodcastController.showPublishedEpisode);
router.get('/about', aboutController.showAbout);
router.get('/help', helpController.showHelp);
router.get('/terms', legalController.showTerms);
router.get('/privacy-policy', legalController.showPrivacyPolicy);
router.get('/cookie-policy', legalController.showCookiePolicy);
router.get('/data-rights', legalController.showDataRights);
router.get('/', landingController.showLanding);

module.exports = router;
